### ISSUE TITLE
partialy written images sometimes server via web client

### ISSUE THREAD

**Issue by mrjones-plip** [NegativeK/picamserver#23] opened 2024-12-07 23:20 UTC
I was refreshing a lot and saw this image (note missing bottom portion):

![image](https://github.com/user-attachments/assets/5405e249-4438-4498-85af-864ab0d4d7ae)

I think is because we write to the exact same location we read from. A possible fix to this is to write to `IMAGE_FILE` + tmp and as soon as it's done do a `mv` to the real location.  The `mv` should be incredibly quick.

**Comment by NegativeK** [comment] 2024-12-08 02:18
Marking as duplicate of #19 . Agreed on the fix path.

**Closed by NegativeK** 2024-12-08 02:18 UTC
Labels: duplicate

**Comment by mrjones-plip** [comment] 2024-12-08 21:14
ah - sorry I didn't check for existing issues. thank you for tidying up!
